spring:
    application:
    name: jpoint-2026-demo
    sql:
        init:
            mode: always
    datasource:
        url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=true
logging:
    level:
        org.springframework.jdbc: DEBUG
